### ISSUE TITLE
Is there an example project somewhere?

### ISSUE THREAD

**Issue by andre-artus** [oldergod/RxDataBinding#3]
This project looks interesting, but I would like to check out an example application showcasing the recommended approach to using this library. Is there, to your knowledge, somewhere I can find one. Or a documentation site/wiki?

**Comment by oldergod** [comment]
I am using one here in my other project https://github.com/oldergod/red/blob/1bdb2617f75c72bc3205585f983e2bbff6c7b0da/app/src/main/java/com/benoitquenaudon/tvfoot/red/app/domain/match/MatchActivity.java#L80-L89

As long as you take care of the observable's lifecycle, every approach should be fine.
